apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - image: okteto.dev/was:latest
        name: was
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "c58412f5-7761-4535-8e4c-14a8858e8767"
        - name: Vless_Path
          value: "/jjshhg"
        - name: Vmess_UUID
          value: "c58412f5-7761-4535-8e4c-14a8858e8767"
        - name: Vmess_Path
          value: "/kloosjh"
        - name: Share_Path
          value: "/share233"
